bitpay/bitpay-browser-extension

src/manifest/index.js
src/popup/components/line-items/line-items.scss
src/popup/components/line-items/line-items.tsx
src/popup/components/pay-with-bitpay/pay-with-bitpay.tsx
src/popup/pages/amount/amount.tsx

- fix manifest project URL
- fix Line Items "Total Cost" positioning
- change view mode to 'popup' when launching invoice
- prevent setState if Amount field is empty (prevents rerender)

Minor Fixes

---

src/popup/components/ios-switch/ios-switch.tsx

create a new objects for unused props to avoid materialUI warning.

Fix material ui warning

---

src/popup/components/line-items/line-items.scss
src/popup/components/line-items/line-items.tsx
src/services/gift-card.types.ts

Clicking Amount Paid value now opens the Invoice in a new tab

Link Amount Paid to Invoice

---

src/popup/components/gravatar/gravatar.tsx
src/popup/components/line-items/line-items.tsx
src/popup/components/navbar/bp-logo/bp-logo.tsx

- fixes jumping logo when amount is prefilled during checkout and invoice is created
- open all invoice links with popup flag
- increase resolution of gravatar to 4x for retina displays
- change default gravatar icon to bitpay's round logo instead of generic profile icon

Navbar: Fix Jumping Logo on Auto Checkout

---

.eslintrc.json
package.json
src/popup/components/gravatar/gravatar.spec.tsx
src/popup/components/super-toast/super-toast.scss
src/popup/components/super-toast/super-toast.spec.tsx
src/popup/components/super-toast/super-toast.tsx
src/setupTests.ts
yarn.lock

Setup Unit Test and added specs for Gravatar and SuperToast components.

Setup Unit test: Jest + enzyme

---

.eslintrc.json
src/popup/components/line-items/line-items.tsx
src/popup/components/navbar/bp-logo/bp-logo.tsx
src/popup/components/navbar/navbar.tsx
src/popup/pages/category/category.scss
src/popup/pages/category/category.tsx
src/popup/pages/shop/shop.scss
src/popup/pages/shop/shop.tsx
src/popup/popup.tsx
src/services/directory.ts
src/styles/_variables.scss

- adds basic category functionality
1. resize behaviour when navigating to category page
2. retain scroll position after selecting category and also scoping into brand
3. need to hide categories that are empty

Categories

---

src/popup/components/search-bar/search-bar.spec.tsx
src/popup/components/search-bar/search-bar.tsx
src/popup/components/wallet-cards/wallet-card.spec.tsx
src/popup/components/wallet-cards/wallet-card.tsx

Add specs for:
Wallet-card
Search-bar

Add wallet card and search bar tests

---

src/content-script/drag.ts
src/content-script/index.ts
src/popup/components/action-button/action-button.scss

- fix box shadow transition on drag
- tweak drag box-shadow to be a bit more natural (we can keep tweaking this guy)
- tweak button footer shadow to be a bit more subtle

Minor Tweaks 1

---

src/content-script/drag.ts
src/content-script/index.ts

- increase drag shadow depth and make base frame shadow and bit harder for better contrast and perception of close proximity to page

Drag Shadow Update 2

---

src/background/index.ts

After creating popup window if window size not equal to the specified height/width then update the window size.

Fix popup win size

---

src/popup/components/navbar/back-button/back-button.scss
src/popup/components/pay-with-bitpay/pay-with-bitpay.scss
src/popup/components/pay-with-bitpay/pay-with-bitpay.tsx
src/popup/components/search-bar/search-bar.scss
src/popup/pages/category/category.scss
src/popup/pages/category/category.tsx
src/popup/pages/settings/account/account.scss
src/popup/pages/settings/account/account.tsx
src/services/animations.ts
src/styles/_animations.scss
src/styles/_variables.scss

adds animations to Pay with BitPay + Sign in with BitPay buttons

Animation: Awaiting Payment & Awaiting Auth

---

src/popup/components/merchant-cta/merchant-cta.scss
src/popup/pages/shop/shop.tsx

- order categories on Shop page alphabetically

Shop: Alphabetize Categories

---

src/popup/components/search-bar/search-bar.scss
src/popup/components/search-bar/search-bar.tsx
src/popup/pages/shop/shop.scss

- animate shadow into view when scrolling

Feat: Search Bar Shadow on Scroll

---

src/popup/components/search-bar/search-bar.scss
src/styles/_reset.scss

- normalize search bar interior margin
- simplify hidden scroll bar style

Minor Tweaks 2

---

src/popup/pages/brand/brand.scss
src/popup/pages/brand/brand.tsx

-  normalize discount pill styles

Minor Tweaks 3

---

src/popup/components/card-header/card-header.tsx
src/popup/components/line-items/line-items.tsx
src/popup/components/navbar/bp-logo/bp-logo.tsx
src/popup/pages/card/balance/balance.tsx
src/popup/pages/card/card.tsx
src/popup/pages/payment/payment.tsx
src/popup/pages/wallet/wallet.tsx
src/services/animations.ts

- animates gift card details view
- disable animation for Edit Balance & Payment views

Animate Gift Card View

---

README.md

Signed-off-by: Ash Bhimasani <abhimasani@bitpay.com>

Update README with graphics

---

README.md
package.json
src/popup/components/line-items/line-items.tsx
src/popup/components/search-bar/search-bar.tsx
src/services/merchant.ts
yarn.lock

Signed-off-by: Ash Bhimasani <abhimasani@bitpay.com>

Fix Line Items: Remove redundant Discount text

---

src/popup/components/tabs/tabs.scss

Fix Tabs for latest browsers

---

package.json
src/content-script/index.ts
src/popup/components/card-menu/card-menu.scss
src/popup/pages/card/card.tsx

Allows users to print a gift card for use in-store. Also ensures users are able to connect their account.

Implement Print Functionality
